# Generated by Django 3.2.9 on 2021-11-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('passengers', models.IntegerField(default=0)),
                ('luggage', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
